### ISSUE TITLE
Due to pessimistic dependency constraints, unable to use with latest windows/chef-sugar cookbooks

### ISSUE THREAD

**Issue by sgtcoolguy** [emachnic/chef-rubyinstaller#1]
I was unable to drop this into my own wrapper cookbook due to the pessimistic version constraints on chef-sugar and windows dependencies. I don't believe the newer versions of those cookbooks break this one, so opening up the version constraints some might help people use it more freely.

(I was using chef-sugar 3.4.0 and windows 2.1.1)

Additionally, given such a small cookbook, you may want to consider dropping the dependency on chef-sugar (which is very nice, but I think maybe you're simply using it to shorten `platform?('windows')` to `windows?`)

**Comment by emachnic** [comment]
@sgtcoolguy Thanks for letting me know. Working on updating the cookbook now.

**Comment by emachnic** [comment]
@sgtcoolguy I just pushed out a new version. Can you check if it works for you?

**Comment by emachnic** [comment]
I'm going to close this as I haven't heard back. If this is still an issue, then we can reopen.
